import{z}from"zod";
export const scheduleEventSchema=z.object({title:z.string().trim().min(1).max(160),date:z.iso.date(),allDay:z.boolean(),startTime:z.string().regex(/^\d{2}:\d{2}$/).optional(),endTime:z.union([z.literal(""),z.string().regex(/^\d{2}:\d{2}$/)]).optional(),location:z.string().trim().max(240).optional(),category:z.enum(["household","family","school","work","appointment","celebration"]),notes:z.string().trim().max(2000).optional(),participantIds:z.array(z.uuid()).default([]),recurrence:z.enum(["","daily","weekly","monthly","yearly"]),reminderMinutes:z.union([z.literal(""),z.coerce.number().int().min(0).max(10080)])});
export type ScheduleEventInput=z.infer<typeof scheduleEventSchema>;
export function parseScheduleEventForm(formData:FormData){const allDay=formData.get("allDay")==="on";return scheduleEventSchema.safeParse({title:formData.get("title"),date:formData.get("date"),allDay,startTime:allDay?undefined:String(formData.get("startTime")??""),endTime:allDay?undefined:String(formData.get("endTime")??""),location:String(formData.get("location")??""),category:formData.get("category"),notes:String(formData.get("notes")??""),participantIds:formData.getAll("participantIds"),recurrence:String(formData.get("recurrence")??""),reminderMinutes:String(formData.get("reminderMinutes")??"")})}
function offsetMinutes(date:Date,timeZone:string){const parts=new Intl.DateTimeFormat("en-US",{timeZone,timeZoneName:"longOffset",hour:"2-digit"}).formatToParts(date);const value=parts.find(part=>part.type==="timeZoneName")?.value??"GMT+00:00";const match=value.match(/GMT([+-])(\d{2}):(\d{2})/);if(!match)return 0;return(match[1]==="+"?1:-1)*(Number(match[2])*60+Number(match[3]))}
export function householdLocalDateTimeToIso(date:string,time:string,timeZone:string){const[year,month,day]=date.split("-").map(Number);const[hour,minute]=time.split(":").map(Number);let instant=new Date(Date.UTC(year,month-1,day,hour,minute));for(let attempt=0;attempt<2;attempt++)instant=new Date(Date.UTC(year,month-1,day,hour,minute)-offsetMinutes(instant,timeZone)*60000);return instant.toISOString()}
export function buildScheduleEventRow(value:ScheduleEventInput,context:{householdId:string;familyMemberId:string;timeZone:string}){if(!value.allDay&&!value.startTime)return null;const startsAt=value.allDay?null:householdLocalDateTimeToIso(value.date,value.startTime!,context.timeZone);const endsAt=value.allDay?null:value.endTime&&value.endTime>value.startTime!?householdLocalDateTimeToIso(value.date,value.endTime,context.timeZone):new Date(new Date(startsAt!).getTime()+3600000).toISOString();return{household_id:context.householdId,created_by_member_id:context.familyMemberId,title:value.title,description:value.notes||null,category:value.category,location:value.location||null,is_all_day:value.allDay,all_day_date:value.allDay?value.date:null,recurrence:value.recurrence||null,reminder_minutes:value.reminderMinutes===""?null:value.reminderMinutes,starts_at:startsAt,ends_at:endsAt,cancelled_at:null}}
export const isoDate=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
export function startOfCalendarWeek(value:string){const date=new Date(`${value}T12:00:00`);date.setDate(date.getDate()-((date.getDay()+6)%7));return isoDate(date)}
export function calendarRangeContains(eventDate:string,selected:string,view:"day"|"week"|"month"){if(view==="day")return eventDate===selected;if(view==="week"){const start=startOfCalendarWeek(selected);const end=new Date(`${start}T12:00:00`);end.setDate(end.getDate()+6);return eventDate>=start&&eventDate<=isoDate(end)}const d=new Date(`${selected}T12:00:00`);return eventDate.startsWith(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`)}
export const isUpcomingEvent=(eventDate:string,today:string)=>eventDate>today;
