import Link from "next/link";
import { Card } from "@/components/design-system";
import { FeaturePage, FeaturePageHeader, FeatureSection, ResponsiveGrid, SummaryCard } from "@/components/features/FeaturePage";
import { requireCurrentHouseholdContext } from "@/lib/auth/context";
import { getHouseholdWeather } from "@/lib/weather/service";
import styles from "./weather.module.css";

const timeLabel = (value: string) => { const [hourValue, minute = "00"] = value.slice(11, 16).split(":"); const hour = Number(hourValue); return `${hour % 12 || 12}:${minute} ${hour < 12 ? "AM" : "PM"}`; };
const dayLabel = (value: string) => new Intl.DateTimeFormat(undefined, { weekday: "short", month: "short", day: "numeric", timeZone: "UTC" }).format(new Date(`${value}T12:00:00Z`));

export default async function WeatherPage() {
  const context = await requireCurrentHouseholdContext();
  const state = await getHouseholdWeather(context);
  const canConfigure = context.role === "household_manager";
  if (state.status === "no-location") return <FeaturePage><FeaturePageHeader eyebrow="Household weather" title="Weather" description="A calm look at the conditions around your family home."/><FeatureSection title="Choose a location"><Card><p>{canConfigure ? "Choose your household weather location in Settings to begin." : "A household manager can choose the family weather location in Settings."}</p>{canConfigure ? <Link href="/settings#weather-location">Open weather settings →</Link> : null}</Card></FeatureSection></FeaturePage>;
  if (state.status === "unavailable") return <FeaturePage><FeaturePageHeader eyebrow="Household weather" title="Weather" description="A calm look at the conditions around your family home."/><FeatureSection title="Weather is unavailable right now"><Card><p>The rest of your family headquarters is still ready.</p><Link href="/weather">Try again</Link></Card></FeatureSection></FeaturePage>;
  const weather = state.data;
  return <FeaturePage><FeaturePageHeader eyebrow={weather.location.displayName} title={`${weather.current.condition.label}, ${Math.round(weather.current.temperature)}${weather.unitSymbol}`} description={weather.practicalNote}/>{weather.stale ? <p className={styles.stale} role="status">Last updated {new Date(weather.updatedAt).toLocaleString()}. This forecast may be out of date.</p> : null}<FeatureSection title="Current conditions"><ResponsiveGrid columns={3}><SummaryCard title="Feels like" detail={`${Math.round(weather.current.feelsLike)}${weather.unitSymbol}`} variant="sage"/><SummaryCard title="Wind" detail={`${Math.round(weather.current.windSpeed)} ${weather.windUnit}, gusts ${Math.round(weather.current.windGusts)} ${weather.windUnit}`} variant="neutral"/><SummaryCard title="Precipitation" detail={`${weather.current.precipitation} ${weather.precipitationUnit}`} variant="blush"/></ResponsiveGrid></FeatureSection><FeatureSection title="The rest of today"><div className={styles.hourly}>{weather.hourly.slice(0,12).map((hour)=><Card key={hour.time}><time dateTime={hour.time}>{timeLabel(hour.time)}</time><span role="img" aria-label={hour.condition.label}>{hour.condition.icon}</span><strong>{Math.round(hour.temperature)}{weather.unitSymbol}</strong><small>{hour.precipitationProbability}% precipitation</small></Card>)}</div></FeatureSection><FeatureSection title="Tomorrow and the week ahead"><div className={styles.daily}>{weather.daily.slice(1).map((day)=><Card key={day.date}><time dateTime={day.date}>{dayLabel(day.date)}</time><span role="img" aria-label={day.condition.label}>{day.condition.icon}</span><h3>{day.condition.label}</h3><p>High {Math.round(day.high)}{weather.unitSymbol} · Low {Math.round(day.low)}{weather.unitSymbol}</p><small>{day.precipitationProbability}% precipitation</small></Card>)}</div></FeatureSection><FeatureSection title="Sun and sky"><ResponsiveGrid columns={3}><SummaryCard title="Sunrise" detail={timeLabel(weather.today.sunrise)}/><SummaryCard title="Sunset" detail={timeLabel(weather.today.sunset)}/><SummaryCard title="Maximum UV index" detail={weather.today.uvIndex == null ? "Unavailable" : String(weather.today.uvIndex)}/></ResponsiveGrid></FeatureSection><p className={styles.attribution}>Weather data by <a href="https://open-meteo.com/" target="_blank" rel="noreferrer">Open-Meteo</a>.</p></FeaturePage>;
}