import { existsSync, readFileSync } from "node:fs";
import { createClient } from "@supabase/supabase-js";
for (const path of [".env.local", ".env.test.local"]) { if (!existsSync(path)) continue; for (const line of readFileSync(path, "utf8").split(/\r?\n/)) { const match = line.match(/^([A-Z0-9_]+)=(.*)$/); if (match && !process.env[match[1]]) process.env[match[1]] = match[2].replace(/^["']|["']$/g, ""); } }
const required = ["NEXT_PUBLIC_SUPABASE_URL", "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY", "OFH_TEST_MANAGER_A_EMAIL", "OFH_TEST_MANAGER_A_PASSWORD", "OFH_TEST_MANAGER_B_EMAIL", "OFH_TEST_MANAGER_B_PASSWORD"];
for (const name of required) if (!process.env[name]) throw new Error(`Missing ${name}`);
async function login(emailName, passwordName) { const client = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY, { auth: { persistSession: false, autoRefreshToken: false } }); const auth = await client.auth.signInWithPassword({ email: process.env[emailName], password: process.env[passwordName] }); if (auth.error) throw new Error(`Authentication failed: ${emailName}`); const membership = await client.from("household_memberships").select("household_id").eq("user_id", auth.data.user.id).eq("status", "active").single(); if (membership.error) throw new Error("Membership resolution failed"); return { client, householdId: membership.data.household_id }; }
const geocodeUrl = new URL("https://geocoding-api.open-meteo.com/v1/search"); geocodeUrl.searchParams.set("name", "Raleigh"); geocodeUrl.searchParams.set("count", "5"); geocodeUrl.searchParams.set("language", "en"); geocodeUrl.searchParams.set("format", "json");
const geocodeResponse = await fetch(geocodeUrl, { signal: AbortSignal.timeout(8000) }); if (!geocodeResponse.ok) throw new Error(`Geocoding HTTP ${geocodeResponse.status}`); const geocode = await geocodeResponse.json(); const place = geocode.results?.find((item) => item.country === "United States" && item.admin1 === "North Carolina") ?? geocode.results?.[0]; if (!place?.latitude || !place?.longitude || !place?.timezone) throw new Error("Geocoding transformation fixture not found");
const forecastUrl = new URL("https://api.open-meteo.com/v1/forecast"); forecastUrl.searchParams.set("latitude", String(place.latitude)); forecastUrl.searchParams.set("longitude", String(place.longitude)); forecastUrl.searchParams.set("timezone", place.timezone); forecastUrl.searchParams.set("forecast_days", "7"); forecastUrl.searchParams.set("temperature_unit", "fahrenheit"); forecastUrl.searchParams.set("current", "temperature_2m,apparent_temperature,weather_code,precipitation,rain,snowfall,wind_speed_10m,wind_gusts_10m,is_day"); forecastUrl.searchParams.set("hourly", "temperature_2m,apparent_temperature,precipitation_probability,precipitation,rain,snowfall,weather_code,wind_speed_10m,wind_gusts_10m,is_day"); forecastUrl.searchParams.set("daily", "weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,precipitation_sum,sunrise,sunset,uv_index_max");
const forecastResponse = await fetch(forecastUrl, { signal: AbortSignal.timeout(8000) }); if (!forecastResponse.ok) throw new Error(`Forecast HTTP ${forecastResponse.status}`); const forecast = await forecastResponse.json(); if (!forecast.current?.temperature_2m || forecast.daily?.time?.length !== 7 || !forecast.hourly?.time?.length) throw new Error("Forecast response missing required fields");
const managerA = await login("OFH_TEST_MANAGER_A_EMAIL", "OFH_TEST_MANAGER_A_PASSWORD"); const managerB = await login("OFH_TEST_MANAGER_B_EMAIL", "OFH_TEST_MANAGER_B_PASSWORD");
const columns = "weather_city,weather_region,weather_postal_code,weather_country,weather_display_name,weather_latitude,weather_longitude,weather_time_zone,weather_temperature_unit";
const ownRead = await managerA.client.from("households").select(columns).eq("id", managerA.householdId).single(); if (ownRead.error) throw new Error(`Weather column verification failed: ${ownRead.error.code}`);
const ownWrite = await managerA.client.from("households").update({ weather_temperature_unit: ownRead.data.weather_temperature_unit }).eq("id", managerA.householdId).select("id"); if (ownWrite.error || ownWrite.data.length !== 1) throw new Error("Household manager weather write failed");
const crossRead = await managerB.client.from("households").select("id").eq("id", managerA.householdId); if (crossRead.error || crossRead.data.length) throw new Error("Cross-household weather read isolation failed");
const crossWrite = await managerB.client.from("households").update({ weather_city: "Denied" }).eq("id", managerA.householdId).select("id"); if (crossWrite.error || crossWrite.data.length) throw new Error("Cross-household weather write isolation failed");
await Promise.all([managerA.client.auth.signOut(), managerB.client.auth.signOut()]);
console.log(`Open-Meteo verification passed: geocoding resolved city-level coordinates/timezone; forecast returned current, ${forecast.hourly.time.length} hourly points, and ${forecast.daily.time.length} local daily forecasts. Weather columns are readable and manager-writable in-household; cross-household read/write remained denied.`);