import { afterEach, describe, expect, it, vi } from "vitest";
import { describeWeatherCode, transformForecastResponse, transformGeocodingResponse } from "@/lib/weather/provider";
import { getForecast } from "@/lib/weather/service";
import type { HouseholdWeatherLocation } from "@/lib/weather/types";

const location: HouseholdWeatherLocation = { city: "Raleigh", region: "North Carolina", country: "United States", displayName: "Raleigh, North Carolina, United States", latitude: 35.78, longitude: -78.64, timeZone: "America/New_York", temperatureUnit: "fahrenheit" };
const forecast = { timezone: "America/New_York", current: { time: "2026-07-26T10:00", temperature_2m: 82, apparent_temperature: 86, weather_code: 1, precipitation: 0, rain: 0, snowfall: 0, wind_speed_10m: 7, wind_gusts_10m: 12, is_day: 1 }, hourly: { time: ["2026-07-26T10:00", "2026-07-27T10:00"], temperature_2m: [82, 84], apparent_temperature: [86, 88], precipitation_probability: [20, 30], precipitation: [0, 0], rain: [0, 0], snowfall: [0, 0], weather_code: [1, 2], wind_speed_10m: [7, 8], wind_gusts_10m: [12, 14], is_day: [1, 1] }, daily: { time: ["2026-07-26", "2026-07-27"], weather_code: [1, 2], temperature_2m_max: [90, 91], temperature_2m_min: [70, 71], precipitation_probability_max: [20, 30], precipitation_sum: [0, 0], sunrise: ["2026-07-26T06:15", "2026-07-27T06:16"], sunset: ["2026-07-26T20:22", "2026-07-27T20:21"], uv_index_max: [8, 7] } };

afterEach(() => vi.unstubAllGlobals());
describe("Open-Meteo transformations", () => {
  it("normalizes a geocoding result without a precise address", () => { const result = transformGeocodingResponse({ results: [{ name: "Raleigh", admin1: "North Carolina", country: "United States", latitude: 35.78, longitude: -78.64, timezone: "America/New_York" }] }, { city: "Raleigh", region: "North Carolina", country: "United States", temperatureUnit: "fahrenheit" }); expect(result).toMatchObject({ displayName: "Raleigh, North Carolina, United States", latitude: 35.78, timeZone: "America/New_York" }); expect(result).not.toHaveProperty("address"); });
  it("transforms household-local current, hourly, and daily data", () => { const result = transformForecastResponse(forecast, location, new Date("2026-07-26T14:00:00Z")); expect(result.today.date).toBe("2026-07-26"); expect(result.hourly).toHaveLength(1); expect(result.daily).toHaveLength(2); expect(result.unitSymbol).toBe("°F"); });
  it("uses Celsius units when selected", () => { const result = transformForecastResponse(forecast, { ...location, temperatureUnit: "celsius" }); expect(result.unitSymbol).toBe("°C"); expect(result.precipitationUnit).toBe("mm"); });
  it("provides family-friendly weather code descriptions", () => { expect(describeWeatherCode(0).label).toBe("Clear"); expect(describeWeatherCode(63).label).toBe("Rain"); expect(describeWeatherCode(75).label).toBe("Snow"); expect(describeWeatherCode(95).label).toBe("Thunderstorms"); });
  it("returns the most recent cache as stale when the provider becomes unavailable", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValueOnce({ ok: true, json: async () => forecast }).mockRejectedValueOnce(new Error("offline"))); const first = await getForecast({ ...location, latitude: 35.781 }); const stale = await getForecast({ ...location, latitude: 35.781 }); expect(first.stale).toBe(false); expect(stale.stale).toBe(true); expect(stale.updatedAt).toBe(first.updatedAt); });
});